# permissions for end users to view incusclustertemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-incus
    app.kubernetes.io/managed-by: kustomize
  name: incusclustertemplate-viewer-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - incusclustertemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - incusclustertemplates/status
  verbs:
  - get
