## Append samples of your project ##
resources:
- infrastructure_v1alpha1_incuscluster.yaml
- infrastructure_v1alpha1_incusmachine.yaml
- infrastructure_v1alpha1_incusclustertemplate.yaml
- infrastructure_v1alpha1_incusmachinetemplate.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
